sudo: required

addons:
  firefox: "30.0"
    
language: ruby

rvm:
  - "2.0.0"
  
env:
  global:
    - CI_NODE_TOTAL=6
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flashplugin-installer
  - "gem install cucumber"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start --server-args="-screen 0 1024x768x24"

script: "bundle exec rake play"


#script:
#- "bundle exec rake knapsack:features"
#- "KNAPSACK_GENERATE_REPORT=true bundle exec rake features"
